-- Active: 1708628626646@@localhost@3306@testdb
CREATE DATABASE hbtn_0c_0;
USE hbtn_0c_0;
CREATE TABLE IF NOT EXISTS first_table(
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) DEFAULT NULL,
    c CHAR(1) DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    PRIMARY KEY(id)
);
SELECT * FROM first_table;